WITH D AS (SELECT NAME, ROWNUM RID FROM (SELECT NAME FROM OCCUPATIONS WHERE OCCUPATION = 'Doctor' ORDER BY 1)),
P AS (SELECT NAME, ROWNUM RID FROM (SELECT NAME FROM OCCUPATIONS WHERE OCCUPATION = 'Professor' ORDER BY 1)),
S AS (SELECT NAME, ROWNUM RID FROM (SELECT NAME FROM OCCUPATIONS WHERE OCCUPATION = 'Singer' ORDER BY 1)),
A AS (SELECT NAME, ROWNUM RID FROM (SELECT NAME FROM OCCUPATIONS WHERE OCCUPATION = 'Actor' ORDER BY 1))
SELECT D.NAME, P.NAME, S.NAME, A.NAME 
FROM P
FULL OUTER JOIN D ON P.RID = D.RID
FULL OUTER JOIN A ON P.RID = A.RID
FULL OUTER JOIN S ON P.RID = S.RID;